// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pigoiwdkwdrrodftbkkm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBpZ29pd2Rrd2Rycm9kZnRia2ttIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3MzI5OTEsImV4cCI6MjA3MDMwODk5MX0.qwa02edFDfixXIOqSWq5t378yzb7BT33wkiWa2ssTH4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});